import type { Client, Movement } from "./types";

export const demoClients: Client[] = [
  {
    id: "client-ana",
    code: "C001",
    name: "Ana Perez",
    alias: "Familia Perez",
    phone: "6677-1001",
    notes: "Paga por transferencia casi siempre.",
    bankTags: ["ana perez", "familia perez", "c001"],
    createdAt: "2026-01-10",
  },
  {
    id: "client-rivas",
    code: "C002",
    name: "Comercial Rivas",
    alias: "Rivas",
    phone: "6455-2208",
    notes: "A veces manda soporte por WhatsApp.",
    bankTags: ["comercial rivas", "rivas", "c002"],
    createdAt: "2026-01-15",
  },
  {
    id: "client-faro",
    code: "C003",
    name: "Taller El Faro",
    alias: "Faro",
    phone: "6122-8814",
    notes: "Cuenta al dia.",
    bankTags: ["taller el faro", "faro", "c003"],
    createdAt: "2026-02-04",
  },
  {
    id: "client-maria",
    code: "C004",
    name: "Maria Gonzalez",
    alias: "Maria",
    phone: "6999-0042",
    notes: "Conviene llamarla antes de cerrar mes.",
    bankTags: ["maria gonzalez", "maria", "c004"],
    createdAt: "2026-02-20",
  },
];

export const demoMovements: Movement[] = [
  {
    id: "mov-1",
    clientId: "client-ana",
    date: "2026-03-01",
    type: "cargo",
    amount: 320,
    description: "Cargo por servicio de marzo",
    source: "system",
  },
  {
    id: "mov-2",
    clientId: "client-ana",
    date: "2026-04-02",
    type: "abono",
    amount: 120,
    description: "Abono recibido y anotado por caja",
    source: "manual",
  },
  {
    id: "mov-3",
    clientId: "client-ana",
    date: "2026-04-01",
    type: "cargo",
    amount: 320,
    description: "Cargo por servicio de abril",
    source: "system",
  },
  {
    id: "mov-4",
    clientId: "client-rivas",
    date: "2026-03-05",
    type: "cargo",
    amount: 540,
    description: "Cuenta abierta del mes",
    source: "system",
  },
  {
    id: "mov-5",
    clientId: "client-rivas",
    date: "2026-04-03",
    type: "abono",
    amount: 300,
    description: "Pago parcial recibido por oficina",
    source: "manual",
  },
  {
    id: "mov-6",
    clientId: "client-rivas",
    date: "2026-04-03",
    type: "ajuste",
    amount: -40,
    description: "Ajuste por nota de credito",
    source: "manual",
  },
  {
    id: "mov-7",
    clientId: "client-faro",
    date: "2026-04-01",
    type: "cargo",
    amount: 250,
    description: "Cuenta mensual",
    source: "system",
  },
  {
    id: "mov-8",
    clientId: "client-faro",
    date: "2026-04-04",
    type: "abono",
    amount: 250,
    description: "Pago conciliado con banco",
    source: "bank",
    bankReference: "DEP-8801",
    reconciledAt: "2026-04-04",
  },
  {
    id: "mov-9",
    clientId: "client-maria",
    date: "2026-03-12",
    type: "cargo",
    amount: 410,
    description: "Cargo de marzo",
    source: "system",
  },
  {
    id: "mov-10",
    clientId: "client-maria",
    date: "2026-03-21",
    type: "abono",
    amount: 100,
    description: "Abono recibido en caja",
    source: "manual",
  },
  {
    id: "mov-11",
    clientId: "client-maria",
    date: "2026-04-02",
    type: "cargo",
    amount: 410,
    description: "Cargo de abril",
    source: "system",
  },
];

export const demoBankCsv = `fecha,referencia,cliente,monto
2026-04-02,DEP-9001,Ana Perez,120.00
2026-04-03,DEP-9002,Comercial Rivas,300.00
2026-04-04,DEP-9003,Maria Gonzalez,80.00
2026-04-05,DEP-9004,Cliente por revisar,50.00`;
